name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A285A9E4B66A4BEBA3220191AD0D4D65 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_31FCC2159E854AA7AEBDDCE11F0F339E }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BD40E05D860B45C2BEC73342B6922430 }}

    - name: Log in to ACR
      run: az acr login --name ragdockerimage

    - name: Build and Push Docker image
      run: |
        docker build -t ragdockerimage.azurecr.io/rag:latest .
        docker push ragdockerimage.azurecr.io/rag:latest
